[programs.localnet]
solana_twitter = "25GgtRTrVAYh1Tz6BJAw1eJmojjyf7EffUU8xoWuwyRR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id-dev.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
custom-test = "echo 'Hello World'"